"""BlacUSA seed content: articles, cold cases, membership tiers.
Realistic placeholder editorial data for V1 look-and-feel.
"""

IMG = {
    "voting": "https://images.pexels.com/photos/7102965/pexels-photo-7102965.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "voting2": "https://images.unsplash.com/photo-1597701548622-cf60627fd70a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "health": "https://images.pexels.com/photos/18870282/pexels-photo-18870282.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "health2": "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "street": "https://images.unsplash.com/photo-1627927518258-b67557570840?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "street2": "https://images.unsplash.com/photo-1616113364365-b6013f3dad25?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "enviro": "https://images.pexels.com/photos/9886298/pexels-photo-9886298.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "court": "https://images.unsplash.com/photo-1636652966850-5ac4d02370e9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "court2": "https://images.unsplash.com/photo-1483600516620-7254872369ae?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "solutions": "https://images.unsplash.com/photo-1573497701240-345a300b8d36?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "coop": "https://images.pexels.com/photos/8761679/pexels-photo-8761679.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "leader": "https://images.pexels.com/photos/6170564/pexels-photo-6170564.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "vigil": "https://images.unsplash.com/photo-1573179329358-957d1c78547c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
    "candles": "https://images.unsplash.com/photo-1476873282730-9018f17bdf4e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400",
}

CATEGORIES = [
    {"slug": "politics", "name": "Politics", "blurb": "Power, policy, and the people it touches."},
    {"slug": "health-equity", "name": "Health Equity", "blurb": "Closing the gaps in care and outcomes."},
    {"slug": "criminal-justice", "name": "Criminal Justice", "blurb": "Accountability, reform, and the road to fairness."},
    {"slug": "environmental-racism", "name": "Environmental Racism", "blurb": "Who breathes the cleanest air, and who pays."},
    {"slug": "solutions", "name": "Solutions", "blurb": "How communities are answering hard problems."},
    {"slug": "rural", "name": "Rural", "blurb": "The Black South and the overlooked countryside."},
]

ARTICLES = [
    {
        "slug": "the-quiet-machine-rebuilding-black-voter-power-in-georgia",
        "title": "The Quiet Machine Rebuilding Black Voter Power in Georgia",
        "dek": "Away from the cameras, a network of barbershops, churches and porch conversations is turning out voters the polls forgot.",
        "category": "politics",
        "author": "Maya Ellison",
        "author_role": "Senior Politics Correspondent",
        "read_minutes": 9,
        "is_solutions": True,
        "is_featured": True,
        "image": IMG["voting2"],
        "content_warning": None,
        "tags": ["voting rights", "organizing", "Georgia"],
        "body": [
            "In the back of a barbershop on Auburn Avenue, the work of democracy looks nothing like a campaign rally. There are no podiums, no slogans printed on glossy cards. There is a clipboard, a folding chair, and a man named Cornelius who has registered four hundred voters one haircut at a time.",
            "For decades, the conventional wisdom held that Black turnout in the rural and exurban South was a problem of apathy. The organizers gathering here every Tuesday reject that framing entirely. The problem, they argue, was never indifference. It was infrastructure.",
            "What they have built instead is a reciprocal listening network: a system that begins not with a message to broadcast but with a question to ask. What do you need to vote? What is standing in your way? The answers have reshaped everything from polling-place hours to the design of their door-knocking maps.",
            "This is solutions journalism in practice on the ground level. Rather than chronicling another cycle of suppression, the organizers measure their work in concrete, repeatable wins, the kind that survive a bad news cycle and a hostile algorithm alike.",
            "By the November before last, the precincts touched by this network saw turnout climb by eleven points. The number itself matters less than the method behind it, a method now being copied in four neighboring counties.",
        ],
    },
    {
        "slug": "the-zip-code-that-decides-how-long-you-live",
        "title": "The Zip Code That Decides How Long You Live",
        "dek": "Two neighborhoods, three miles apart, a fourteen-year gap in life expectancy. A new clinic model is trying to close it.",
        "category": "health-equity",
        "author": "Dr. Andre Whitfield",
        "author_role": "Health Equity Reporter",
        "read_minutes": 11,
        "is_solutions": True,
        "is_featured": True,
        "image": IMG["health"],
        "content_warning": None,
        "tags": ["health equity", "maternal health", "access"],
        "body": [
            "On a map of the city, the two neighborhoods are close enough to walk between in under an hour. On a map of human lifespan, they are separated by fourteen years.",
            "The gap is not an accident of biology. It is the cumulative weight of redlining, of pharmacy deserts, of hospital closures that always seem to happen on the same side of the highway.",
            "But this story is not only about the gap. It is about a community health model, run out of a converted storefront, that has begun to narrow it. The clinic meets patients where they are, literally, sending nurse navigators into homes and onto front steps.",
            "Person-first care is the organizing principle here. Patients are not 'non-compliant.' They are people navigating a system that was never designed with them in mind, and the clinic's job is to redesign the encounter around them.",
            "Early data is cautious but promising: a measurable drop in emergency-room visits, and a maternal-health program that has not lost a mother in three years of operation.",
        ],
    },
    {
        "slug": "after-the-verdict-what-accountability-actually-looks-like",
        "title": "After the Verdict: What Accountability Actually Looks Like",
        "dek": "A year on from a landmark consent decree, residents and reformers ask whether anything on the street has truly changed.",
        "category": "criminal-justice",
        "author": "Tariq Bishop",
        "author_role": "Criminal Justice Editor",
        "read_minutes": 13,
        "is_solutions": False,
        "is_featured": True,
        "image": IMG["court"],
        "content_warning": "This article discusses police violence and its aftermath.",
        "tags": ["police reform", "accountability", "consent decree"],
        "body": [
            "Accountability is easy to announce and difficult to measure. A year after the consent decree was signed with great ceremony, the question residents keep asking is the simplest and the hardest: has anything actually changed?",
            "We reviewed twelve months of stop data, sat in on community-review-board meetings, and spoke with two dozen residents, officers, and organizers. The picture that emerges is neither triumph nor failure. It is a slow, contested negotiation over what safety means.",
            "We have approached this reporting with a trauma-informed framework. The families we interviewed were given full agency over how they and their loved ones are described, and over which images appear alongside their words.",
            "Some metrics have improved. Use-of-force complaints are down. Others have not moved at all. And in the gap between the paperwork and the lived experience of the street, the real story lives.",
        ],
    },
    {
        "slug": "the-air-they-breathe-a-fight-on-the-fenceline",
        "title": "The Air They Breathe: A Fight on the Fenceline",
        "dek": "For families living in the shadow of a petrochemical plant, the data finally caught up with what their bodies always knew.",
        "category": "environmental-racism",
        "author": "Simone Carter",
        "author_role": "Environment Correspondent",
        "read_minutes": 10,
        "is_solutions": True,
        "is_featured": False,
        "image": IMG["enviro"],
        "content_warning": None,
        "tags": ["environmental racism", "air quality", "fenceline"],
        "body": [
            "The residents of the fenceline neighborhood did not need a study to tell them the air was making them sick. They had the inhalers, the hospital bills, and the funerals.",
            "What they did not have, for years, was data the regulators would accept. This is the story of how a coalition of grandmothers, graduate students and a single donated air monitor changed that.",
            "By building their own network of low-cost sensors, residents produced a dataset too granular to ignore. The readings, mapped block by block, told a story the official monitors miles away had erased.",
            "The campaign that followed is a model of civic journalism in action: not merely reporting the harm, but documenting, step by step, how an organized community forced a response.",
        ],
    },
    {
        "slug": "the-cooperative-grocery-feeding-a-food-desert",
        "title": "The Cooperative Grocery Feeding a Food Desert",
        "dek": "When the last supermarket left town, residents did not wait for another chain. They opened their own and they own it.",
        "category": "solutions",
        "author": "Janelle Ford",
        "author_role": "Solutions Desk",
        "read_minutes": 7,
        "is_solutions": True,
        "is_featured": False,
        "image": IMG["coop"],
        "content_warning": None,
        "tags": ["cooperative", "food access", "ownership"],
        "body": [
            "When the last supermarket pulled out, it took more than groceries. It took the easiest place to run into a neighbor, the after-school job, the produce that did not come from a gas-station shelf.",
            "Rather than wait for a chain to reconsider, residents pooled small shares and opened a cooperative grocery they collectively own. The model is old, the energy is new.",
            "Membership is the engine. Roughly six hundred households now hold a stake, vote on what the store stocks, and share in any surplus at year's end.",
            "It is a reminder that the most durable solutions are often the ones a community owns outright, beyond the reach of a distant boardroom's quarterly math.",
        ],
    },
    {
        "slug": "the-county-with-no-pharmacy",
        "title": "The County With No Pharmacy",
        "dek": "In the rural Black Belt, the nearest prescription can be ninety minutes away. A mobile model is rewriting the map.",
        "category": "rural",
        "author": "Dr. Andre Whitfield",
        "author_role": "Health Equity Reporter",
        "read_minutes": 8,
        "is_solutions": True,
        "is_featured": False,
        "image": IMG["street2"],
        "content_warning": None,
        "tags": ["rural", "pharmacy desert", "Black Belt"],
        "body": [
            "Ninety minutes. That is how far some residents of this Black Belt county must travel to fill a prescription, assuming the car starts and the gas money is there.",
            "Pharmacy deserts are an underreported crisis of the rural South, and they fall hardest on Black communities whose towns lost their independent druggists a generation ago.",
            "A mobile pharmacy, stocked weekly and routed by community request, is one answer being tested here. It is not a cure for the underlying disinvestment, but it is keeping people alive while the larger fight continues.",
        ],
    },
    {
        "slug": "redrawn-the-maps-that-decide-who-gets-heard",
        "title": "Redrawn: The Maps That Decide Who Gets Heard",
        "dek": "A plain-language guide to the redistricting fight in your state and what you can actually do about it.",
        "category": "politics",
        "author": "Maya Ellison",
        "author_role": "Senior Politics Correspondent",
        "read_minutes": 6,
        "is_solutions": False,
        "is_featured": False,
        "image": IMG["voting"],
        "content_warning": None,
        "tags": ["redistricting", "civic guide"],
        "body": [
            "Redistricting sounds like a procedural footnote. It is actually one of the most consequential decisions made about your political voice and it happens largely out of public view.",
            "This is a civic guide, not a lament. Below, in plain language, is how the maps are drawn, where the public hearings are, and how to submit testimony that the commission is legally required to read.",
            "We have stripped out the jargon. Where a deadline matters, we have flagged it. Where a form is required, we have linked it.",
        ],
    },
    {
        "slug": "the-doula-network-saving-black-mothers",
        "title": "The Doula Network Saving Black Mothers",
        "dek": "Facing a maternal mortality crisis, a network of community doulas is changing outcomes one birth at a time.",
        "category": "health-equity",
        "author": "Simone Carter",
        "author_role": "Environment Correspondent",
        "read_minutes": 9,
        "is_solutions": True,
        "is_featured": False,
        "image": IMG["health2"],
        "content_warning": None,
        "tags": ["maternal health", "doulas", "solutions"],
        "body": [
            "Black women in the United States die in childbirth at nearly three times the rate of white women, a disparity that holds across income and education.",
            "Against that backdrop, a network of trained community doulas has begun to bend the curve in one city, pairing expectant mothers with advocates who stay with them from the first appointment through the fourth trimester.",
            "The doulas are not a substitute for systemic reform. But the births they attend show what advocacy at the bedside can accomplish, and the data is hard to argue with.",
        ],
    },
]

# Cold cases: dignified public-record entries with US coordinates.
COLD_CASES = [
    {
        "case_number": "BUS-2019-0412",
        "name": "Denise Marie Holloway",
        "age": 24,
        "sex": "Female",
        "race": "Black",
        "case_type": "Missing Person",
        "status": "Open",
        "date_reported": "2019-06-14",
        "city": "Detroit", "state": "MI",
        "lat": 42.3314, "lng": -83.0458,
        "agency": "Detroit Police Department",
        "agency_phone": "(313) 555-0142",
        "summary": "Denise was last seen leaving her workplace on the east side. Her family describes her as devoted to her two children and in regular contact with her mother. They are asking anyone with information to come forward.",
        "family_note": "Denise's family has asked that she be remembered as a daughter and mother, not a statistic.",
    },
    {
        "case_number": "BUS-2017-1103",
        "name": "Marcus DeShawn Pryor",
        "age": 31,
        "sex": "Male",
        "race": "Black",
        "case_type": "Homicide",
        "status": "Cold",
        "date_reported": "2017-11-03",
        "city": "Chicago", "state": "IL",
        "lat": 41.8781, "lng": -87.6298,
        "agency": "Chicago Police Department",
        "agency_phone": "(312) 555-0177",
        "summary": "Marcus was a youth basketball coach known throughout his South Side neighborhood. His case has seen no public movement in over five years. His mentees continue to advocate for renewed investigation.",
        "family_note": "Loved ones remember a man who showed up early to every practice.",
    },
    {
        "case_number": "BUS-2021-0307",
        "name": "Aaliyah Renée Brooks",
        "age": 17,
        "sex": "Female",
        "race": "Black",
        "case_type": "Missing Person",
        "status": "Open",
        "date_reported": "2021-03-07",
        "city": "Atlanta", "state": "GA",
        "lat": 33.7490, "lng": -84.3880,
        "agency": "Atlanta Police Department",
        "agency_phone": "(404) 555-0199",
        "summary": "Aaliyah, an honor-roll student, did not return home from a study group. Her disappearance received limited initial coverage. Her case is featured here at her family's request.",
        "family_note": "Aaliyah dreamed of studying marine biology.",
    },
    {
        "case_number": "BUS-2015-0820",
        "name": "James Earl Whitmore",
        "age": 46,
        "sex": "Male",
        "race": "Black",
        "case_type": "Civil Rights",
        "status": "Cold",
        "date_reported": "2015-08-20",
        "city": "Birmingham", "state": "AL",
        "lat": 33.5186, "lng": -86.8104,
        "agency": "Jefferson County Sheriff",
        "agency_phone": "(205) 555-0123",
        "summary": "A community advocate, James died under circumstances his family has long disputed. They continue to seek an independent review of the original investigation.",
        "family_note": "James spent his life registering voters across the county.",
    },
    {
        "case_number": "BUS-2020-0529",
        "name": "Tamara Joy Sinclair",
        "age": 29,
        "sex": "Female",
        "race": "Black",
        "case_type": "Homicide",
        "status": "Open",
        "date_reported": "2020-05-29",
        "city": "Houston", "state": "TX",
        "lat": 29.7604, "lng": -95.3698,
        "agency": "Houston Police Department",
        "agency_phone": "(713) 555-0156",
        "summary": "Tamara was a nurse who worked the overnight shift at a local hospital. Investigators have asked the public for help identifying a vehicle seen in the area.",
        "family_note": "Colleagues describe Tamara as the calmest presence on the floor.",
    },
    {
        "case_number": "BUS-2018-0916",
        "name": "Reginald Otis Banks",
        "age": 38,
        "sex": "Male",
        "race": "Black",
        "case_type": "Missing Person",
        "status": "Cold",
        "date_reported": "2018-09-16",
        "city": "New Orleans", "state": "LA",
        "lat": 29.9511, "lng": -90.0715,
        "agency": "New Orleans Police Department",
        "agency_phone": "(504) 555-0188",
        "summary": "Reginald, a musician, was last seen near the riverfront. His bandmates have organized annual searches and continue to keep his case in the public eye.",
        "family_note": "Reginald played trumpet on Frenchmen Street for two decades.",
    },
    {
        "case_number": "BUS-2022-0211",
        "name": "Keisha Lynn Andrews",
        "age": 22,
        "sex": "Female",
        "race": "Black",
        "case_type": "Missing Person",
        "status": "Open",
        "date_reported": "2022-02-11",
        "city": "Philadelphia", "state": "PA",
        "lat": 39.9526, "lng": -75.1652,
        "agency": "Philadelphia Police Department",
        "agency_phone": "(215) 555-0166",
        "summary": "Keisha, a community-college student, was reported missing by her roommate. Surveillance footage placed her near a transit station the morning she disappeared.",
        "family_note": "Keisha was the first in her family to attend college.",
    },
    {
        "case_number": "BUS-2016-0704",
        "name": "Theodore Ray Coleman",
        "age": 52,
        "sex": "Male",
        "race": "Black",
        "case_type": "Homicide",
        "status": "Solved",
        "date_reported": "2016-07-04",
        "city": "Oakland", "state": "CA",
        "lat": 37.8044, "lng": -122.2712,
        "agency": "Oakland Police Department",
        "agency_phone": "(510) 555-0144",
        "summary": "Theodore's case was closed in 2023 following a renewed investigation aided by community tips. His family credits sustained public attention with keeping the case active.",
        "family_note": "Resolution came after seven years of his daughters' advocacy.",
    },
    {
        "case_number": "BUS-2019-1218",
        "name": "Brianna Nicole Hayes",
        "age": 19,
        "sex": "Female",
        "race": "Black",
        "case_type": "Missing Person",
        "status": "Cold",
        "date_reported": "2019-12-18",
        "city": "Memphis", "state": "TN",
        "lat": 35.1495, "lng": -90.0490,
        "agency": "Memphis Police Department",
        "agency_phone": "(901) 555-0133",
        "summary": "Brianna was last seen during the winter holidays. Her case received little attention at the time. Her mother has campaigned for it to be reclassified and reopened.",
        "family_note": "Brianna loved to sing in her church choir.",
    },
    {
        "case_number": "BUS-2021-0925",
        "name": "Darius Malik Freeman",
        "age": 27,
        "sex": "Male",
        "race": "Black",
        "case_type": "Civil Rights",
        "status": "Open",
        "date_reported": "2021-09-25",
        "city": "Minneapolis", "state": "MN",
        "lat": 44.9778, "lng": -93.2650,
        "agency": "Hennepin County Attorney",
        "agency_phone": "(612) 555-0111",
        "summary": "Darius's family is seeking transparency regarding the circumstances of his death in custody. An independent investigation has been requested.",
        "family_note": "Darius was an apprentice electrician and a new father.",
    },
]

MEMBERSHIP_TIERS = [
    {
        "key": "reader",
        "name": "Reader",
        "price": 0,
        "cadence": "forever",
        "tagline": "Open access to the public record.",
        "features": [
            "Full access to all reporting",
            "The complete Cold Case database",
            "Weekly solutions newsletter",
            "Comment in moderated forums",
        ],
        "highlight": False,
    },
    {
        "key": "member",
        "name": "Member",
        "price": 12,
        "cadence": "month",
        "tagline": "Fund the reporting that algorithms ignore.",
        "features": [
            "Everything in Reader",
            "Ad-light reading experience",
            "Monthly investigative briefings",
            "Member-only community events",
            "Early access to special reports",
        ],
        "highlight": True,
    },
    {
        "key": "co-owner",
        "name": "Co-Owner",
        "price": 250,
        "cadence": "one-time share",
        "tagline": "Own a micro-share of the newsroom.",
        "features": [
            "Everything in Member",
            "Equity micro-share in BlacUSA",
            "A vote in newsroom governance",
            "Annual co-op assembly access",
            "Name in the founding co-owner ledger",
        ],
        "highlight": False,
    },
]
